<?php

namespace AppBundle\Repository;

/**
 * AnswerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnswerRepository extends \Doctrine\ORM\EntityRepository
{
    public function loadQuestionAsc($em, $test) {
        $query = $em->createQuery(
            'SELECT answer FROM AppBundle:Answer answer WHERE answer.test = :test ORDER BY answer.question ASC'
        )->setParameter("test", $test);
        return $query->execute();
    }
}
