<?php

namespace AppBundle\Repository;

/**
 * TestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TestRepository extends \Doctrine\ORM\EntityRepository
{
    public function loadAllTestsByDate($em) {
        $query = $em->createQuery(
            'SELECT test FROM AppBundle:Test test ORDER BY test.date DESC'
        );
        return $query->getResult();
    }
}
