<?php

namespace AppBundle\Repository;

/**
 * TestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TestRepository extends \Doctrine\ORM\EntityRepository
{
    public function loadAllTestsByDate($em, $user) {
        $query = $em->createQuery(
            'SELECT test FROM AppBundle:Test test WHERE test.user =:userName ORDER BY test.date DESC'
        )->setParameter('userName', $user);
        return $query->getResult();
    }
}
